#ifndef ASM_SIZES_H
#define ASM_SIZES_H

#define __KERNEL_STACK_SIZE   0x4000
#define __KERNEL_STACK_ALIGN  0x1000

#ifdef LINKER_SCRIPT

KERNEL_STACK_SIZE = __KERNEL_STACK_SIZE;
KERNEL_STACK_ALIGN = __KERNEL_STACK_ALIGN;

#else

#define KERNEL_STACK_SIZE   __KERNEL_STACK_SIZE
#define KERNEL_STACK_ALIGN  __KERNEL_STACK_ALIGN

#endif

#endif
